# Protected by IP.
swarm.anduinos.com {
	log
    import hsts
    import rate_limit
	encode br gzip
    @blocked not remote_ip 172.18.0.0/16

	handle @blocked {
		header Content-Type text/html
		respond "<h1>You shouldn't manage my docker swarm :)</h1>" 401
	}
    reverse_proxy http://swarmpit_app:8080 {
    }
}
