docs.anduinos.com {
	log
	import hsts
	import limit_to_cloudflare

	encode br gzip
	reverse_proxy http://anduinos_docs:5000
}

www.anduinos.com {
	log
	import hsts
	import limit_to_cloudflare

	encode br gzip
	reverse_proxy http://anduinos_app:5000
}

anduinos.com {
	log
	import hsts
	import limit_to_cloudflare

	encode br gzip
	redir https://www.anduinos.com{uri}
}