version: '3.9'

services:
  docs:
    image: hub.aiursoft.com/anduin/anduinos-docs
    networks:
      - proxy_app
    stop_grace_period: 20s
    deploy:
      replicas: 2
      update_config:
        delay: 5s
        order: start-first

  home:
    image: hub.aiursoft.com/anduin/anduinos-home
    networks:
      - proxy_app
    stop_grace_period: 20s
    deploy:
      replicas: 2
      update_config:
        delay: 5s
        order: start-first
      resources:
        limits:
          cpus: '1'
          memory: 2G

networks:
  proxy_app:
    external: true