news.anduinos.com {
	log
	import hsts
	import rate_limit
	encode br gzip
	@hacker {
		not remote_ip 172.18.0.0/16
		path /auth*
	}
	handle @hacker {
		header Content-Type text/html
		respond "<h1>You shouldn't manage my AnduinOS blog :)</h1>" 401
	}
	reverse_proxy http://news_app:5000 {
	}
}