version: '3.9'

services:
  app:
    image: aiursoft/tracer
    volumes:
      - tracer-data:/data
    networks:
      - proxy_app
    stop_grace_period: 20s
    deploy:
      replicas: 3
      update_config:
        delay: 5s
        order: start-first
      resources:
        limits:
          cpus: '1'
          memory: 1G

volumes:
  tracer-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /swarm-vol/tracer/

networks:
  proxy_app:
    external: true
