version: '3.9'

services:
  app:
    image: hub.aiursoft.com/aiursoft/tracer
    volumes:
      - tracer-data:/data
    networks:
      - proxy_app
    stop_grace_period: 20s
    deploy:
      replicas: 3
      update_config:
        delay: 5s
        order: start-first
      resources:
        limits:
          cpus: '1'
          memory: 1G

volumes:
  tracer-data:
    driver: local

networks:
  proxy_app:
    external: true
