# Untrusted.
tracer.anduinos.com {
    tls /data/caddy/certs/anduinos.pem /data/caddy/certs/anduinos.key
	log
	import rate_limit_api

    reverse_proxy http://tracer_app:5000 {
        header_up X-Forwarded-For {http.request.header.Cf-Connecting-Ip}
    }
}
