version: '3.3'

services:
  web:
    image: hub.aiursoft.cn/aiursoft/static
    volumes:
      - download-data:/data
    networks:
      - proxy_app
    deploy:
      replicas: 3
      labels:
        swarmpit.service.deployment.autoredeploy: 'true'
      update_config:
        order: start-first
    entrypoint: ["sh", "-c", "/app/static --port 5000 --path /data --allow-directory-browsing"]

volumes:
  download-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /swarm-vol/download-data

networks:
  proxy_app:
    external: true