download.anduinos.com {
	log
	import hsts
	encode br gzip

	rate_limit {
		zone ip_limit {
			key    {remote_host}
			events 6
			window 10s
		}
		log_key
	}

	reverse_proxy http://download_web:5000
}
