grafana.anduinos.com {
    tls /data/caddy/certs/anduinos.pem /data/caddy/certs/anduinos.key
    log
    import hsts
    import limit_to_cloudflare
    encode br gzip
    reverse_proxy http://grafana_grafana:3000 {
        header_up X-Forwarded-For {http.request.header.Cf-Connecting-Ip}
    }
}
