grafana.anduinos.com {
    tls /data/caddy/certs/anduinos.pem /data/caddy/certs/anduinos.key
    log
    import hsts
    import rate_limit
    encode br gzip
    reverse_proxy http://grafana_grafana:3000 {
    }
}
