version: '3.3'

services:
  app:
    image: gitea/gitea
    volumes:
      - gitea-data:/data
    networks:
      - proxy_app
    ports:
      # These ports are for internal use. For external, FRP will handle it.
      - target: 2201
        published: 2201
        protocol: tcp
        mode: host
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 4096M
      labels:
        swarmpit.service.deployment.autoredeploy: 'true'

volumes:
  gitea-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /swarm-vol/gitea-data

networks:
  proxy_app:
    external: true