version: '3.3'

services:
  docs:
    image: localhost:8080/box_starting/local_docs
    networks:
      - proxy_app
    deploy:
      labels:
        swarmpit.service.deployment.autoredeploy: 'true'


networks:
  proxy_app:
    external: true