version: '3.3'

services:
  docs:
    image: hub.aiursoft.cn/anduin/anduinos-docs
    networks:
      - proxy_app
    deploy:
      replicas: 2
      labels:
        swarmpit.service.deployment.autoredeploy: 'true'

  home:
    image: hub.aiursoft.cn/anduin/anduinos-home
    networks:
      - proxy_app
    deploy:
      replicas: 2
      labels:
        swarmpit.service.deployment.autoredeploy: 'true'


networks:
  proxy_app:
    external: true