version: '3.3'

services:
  web:
    image: hub.aiursoft.cn/aiursoft/static:latest
    volumes:
      - download-data:/data
    networks:
      - proxy_app
    stop_grace_period: 20s
    deploy:
      replicas: 3
      update_config:
        delay: 5s
        order: start-first
      resources:
        limits:
          cpus: '1'
          memory: 1G
    entrypoint: ["sh", "-c", "/app/static --port 5000 --path /data --allow-directory-browsing"]

volumes:
  download-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /swarm-vol/download-data

networks:
  proxy_app:
    external: true