download.anduinos.com {
	tls /data/caddy/certs/anduinos.pem /data/caddy/certs/anduinos.key
	log
	import hsts
	import rate_limit
	encode br gzip

	rate_limit {
		zone ip_limit {
			key    {remote_host}
			events 6
			window 10s
		}
		log_key
	}

	reverse_proxy http://download_web:5000
}
